resources:         
  repositories:
  - repository: ForMindTree      
    type: GitHub
    connection: GithubCloud_Mindtree
    source: harirampalanisamy/ForMindTree
    pr: 
      branches:
      - main

pool:
  vmImage: windows-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
